from tasks import task1, utils 
import unittest
import pandas as pd

# Test cases have been generated by hand
# Comprehensive fuzzy testing has not been included due to time constraints
class Task1Test(unittest.TestCase): 
    # City for The Drunken Botanist has been removed
    # Name for Jungle Jamboree has been removed       
    def test_missing_key(self):
        rawData = utils.getJsonLocal("inputs/restaurant_missing_key.json")
        task1.main(rawData)
        
        dfExpect = pd.read_csv("expected_outputs/restaurant_missing_key.csv")
        df = pd.read_csv("outputs/restaurants.csv")

        assert(dfExpect.equals(df))

    # El patio and Aprazível have been edited to "", indicating empty values
    # The Roastery Coffee House cuisine has been edited to ""
    # Aprazível city has been edited to ""
    def test_missing_values(self):
        rawData = utils.getJsonLocal("inputs/restaurant_missing_data.json")
        task1.main(rawData)
        
        dfExpect = pd.read_csv("expected_outputs/restaurant_missing_data.csv")
        df = pd.read_csv("outputs/restaurants.csv")

        assert(dfExpect.equals(df))

if __name__ == '__main__':
    unittest.main()